auth_app/urls.py
from django.urls import path
from .views import CustomAuthToken, register, ListUsers
from . import views

app_name = 'core' 

urlpatterns = [
    path('', views.index, name='index'),
    path('shop/', views.shop_view, name = 'shop'),
    path('users/', views.user_profile,  name = 'users'),
    path('seller/', views.seller_profile, name = 'sellers'),
    path('login/', views.login_view, name = 'login'),
    path('register/', views.register_user, name='reg_user'),
    path('register_seller/', views.register_seller, name='reg_seller'),
    path('home/', views.index, name='home'),
    path('logout/', views.logout_view, name='logout'),
    path('transaction_history/', views.transaction_history, name='transaction_history'),
    path('change-status-delivered/', views.change_status_delivered, name='change_status_delivered'),
    path('change-status/', views.change_status, name='change_status'),
    path('product/<int:id>/', views.single_product, name='single_product'),
    path('adminview/', views.admin_view, name='admin'),
    
    #API URLS
    path('api/users/', ListUsers.as_view(), name='List-users'),
    path('api/token/auth/', CustomAuthToken.as_view(), name='api_token_auth'),
    path('api/register/', register.as_view(), name='Register'),
    path('api/upload_profile_picture/', views.user_profile, name='upload_profile_picture'),
    path('api/add_product/', views.add_product, name='add_product'),
    path('api/seller/<int:seller_id>/products/', views.SellerProductsView.as_view(), name='seller_products'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('remove-from-cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update-cart-item/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('update_product/<int:product_id>/', views.update_product, name='update_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('verify-email/<str:token>/', views.VerifyEmail.as_view(), name='verify-email'),
    path('save-selected-address/', views.save_selected_address, name='save_selected_address'),
    path('save-address/', views.save_address, name='save_address'),
    path('get-addresses/', views.get_addresses, name='get_addresses'),
    path('api/login-data/', views.login_data, name='login-data'),
    path('api/sales-today/', views.sales_today, name='sales-today'),
    path('api/total-sales/', views.total_sales, name='total-sales'),
    path('api/pending-orders/', views.pending_orders, name='pending-orders'),
    path('api/user-creation-data/', views.user_creation_data, name='user-creation-data'),
    path('api/toggle-user-status/<int:user_id>/', views.toggle_user_status, name='toggle_user_status'),
    path('change-admin-passowrd', views.change_admin_password, name='change_admin_password'),
    path('delete-address/', views.delete_address, name='delete_address'),
    path('shop/pagination/', views.shop_pagination, name='shop_pagination'),
    path('save-qr-code/', views.save_qr_code, name='save_qr_code'),
    path('checkout/', views.checkout, name='checkout'),
    path('checkout_cod/', views.checkout_cod, name='checkout_cod'),
    path('api/webhook/', views.stripe_webhook, name='stripe_webhook'),
    path('create-stripe-session/', views.create_stripe_session, name='create_stripe_session'),
    path('get_seller_qrcode/<int:seller_id>/', views.get_seller_qrcode, name='get_seller_qrcode'),
    path('get_proof_of_payment/<int:transaction_id>/', views.get_proof_of_payment, name='get_proof_of_payment'),
    path('submit-subscription/', views.submit_subscription, name='submit_subscription'),
    path('api/accept-subscription/<int:user_id>/', views.accept_subscription, name='accept_subscription'),
    path('api/cancel-subscription/<int:user_id>/', views.cancel_subscription, name='cancel_subscription'),
    path('get_order_details/<str:order_number>/', views.get_order_details, name='get_order_details'),
    path('get_order_details/<str:order_number>/', views.get_order_details, name='get_order_details'),
    path('update_order_status/<str:order_number>/', views.update_order_status, name='update_order_status'),
    path('remove_transaction/<str:order_number>/', views.remove_transaction, name='remove_transaction'),
    path('cancel-order/<str:order_number>/', views.cancel_order, name='cancel_order'),
    path('mark-delivered/<str:order_number>/', views.mark_as_delivered, name='mark_as_delivered'),
    path('update-subscription-status/', views.update_subscription_status, name='update_subscription_status'),
    path('extend-subscription/', views.extend_subscription, name='extend_subscription'),
]

backend/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/templates/partials/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/" />

    <!-- title -->
    <title>ASTIG</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'assets/img/astig.png' %}" />
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet" />
    <!-- fontawesome -->
    <link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}" />
    <!-- bootstrap -->
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" />
    <!-- owl carousel -->
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css' %}" />
    <!-- magnific popup -->
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}" />
    <!-- animate css -->
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}" />
    <!-- mean menu css -->
    <link rel="stylesheet" href="{% static 'assets/css/meanmenu.min.css' %}" />
    <!-- main style -->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <!-- responsive -->
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />
    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="assets/img/favicon.png" />
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet" />
    <!-- fontawesome -->
    <link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}" />
    <!-- bootstrap -->
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" />
    <!-- owl carousel -->
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css' %}" />
    <!-- magnific popup -->
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}" />
    <!-- animate css -->
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}" />
    <!-- mean menu css -->
    <link rel="stylesheet" href="{% static 'assets/css/meanmenu.min.css' %}" />
    <!-- main style -->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <!-- responsive -->
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />
    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'assets/img/astig.png' %}" />
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet" />
    <!-- fontawesome -->
    <link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}" />
    <!-- bootstrap -->
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" />
    <!-- owl carousel -->
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css' %}" />
    <!-- magnific popup -->
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}" />
    <!-- animate css -->
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}" />
    <!-- mean menu css -->
    <link rel="stylesheet" href="{% static 'assets/css/meanmenu.min.css' %}" />
    <!-- main style -->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <!-- responsive -->
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />
  </head>
  <body>
    <!-- PreLoader-->
    <div class="loader">
      <div class="loader-inner">
        <div class="circle"></div>
      </div>
    </div>
    <!--PreLoader Ends -->

    <!-- header -->
    <div class="top-header-area" id="sticker">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-sm-12 text-center">
            <div class="main-menu-wrap">
              <!-- logo -->
              <div class="site-logo">
                <a href="{% url 'core:home' %}">
                  <img src="{% static 'assets/img/astig.png' %}" alt="" style="margin-top: -7.5px; max-width: 60%" />
                </a>
              </div>
              <!-- logo -->

              <!-- menu start -->
              <nav class="main-menu">
                <ul>
                  <li class="{% if request.path == '/home/' %}current-list-item{% endif %}">
                    <a href="{% url 'core:home' %}">Home</a>
                  </li>

                  <li class="{% if request.path == '/shop/' %}current-list-item{% endif %}">
                    <a href="{% url 'core:shop' %}">Shop</a>
                  </li>
                  <li>
                    <div class="header-icons">
                      <a class="shopping-cart" href="{% url 'core:cart_detail' %}">
                        <i class="fas fa-shopping-cart"></i>
                        {% if cart_item_count > 0 %}
                        <span class="cart-count">{{ cart_item_count }}</span>
                        {% endif %}
                      </a>

                      <!-- Add some CSS to style the cart count -->
                      <style>
                        .shopping-cart {
                          position: relative;
                        }
                        .cart-count {
                          position: absolute;
                          top: 5px;
                          right: -3px;
                          background: rgb(255, 104, 104);
                          color: white;
                          border-radius: 50%;
                          padding: 2px 6px;
                          font-size: 8px;
                        }
                      </style>
                      <a class="mobile-hide user-icon" href="{% if user.role == 'Seller' %}{% url 'core:sellers' %}{% else %}{% url 'core:users' %}{% endif %}"
                        ><i class="fas fa-user"></i
                      ></a>

                      <a class="logout-button" href="{% url 'core:logout' %}">Logout</a>
                    </div>
                  </li>
                </ul>
              </nav>

              <div class="mobile-menu"></div>
              <!-- menu end -->
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end header -->

    {% block content %} {% endblock content %}

    <!-- footer -->
    <div class="footer-area">
      <div class="container">
        <div class="row justify-content-center">
          <!-- Add justify-content-center -->

          <div class="col-lg-3 col-md-6">
            <div class="footer-box about-widget">
              <!-- Add text-center -->
              <h2 class="widget-title">About us</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
              </p>
            </div>
          </div>

          <div class="col-lg-3 col-md-6">
            <div class="footer-box get-in-touch">
              <!-- Add text-center -->
              <h2 class="widget-title">Get in Touch</h2>
              <ul>
                <li>Lorem ipsum dolor sit amet</li>
                <li>Lorem ipsum dolor sit amet</li>
                <li>Lorem ipsum dolor sit amet</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end footer -->

    <!-- copyright -->
    <div class="copyright">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-12">
            <p>Copyrights &copy; 2024 - ASTIG, All Rights Reserved.</p>
          </div>
          <div class="col-lg-6 text-right col-md-12">
            <div class="social-icons">
              <ul>
                <li>
                  <a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a>
                </li>
                <li>
                  <a href="#" target="_blank"><i class="fab fa-twitter"></i></a>
                </li>
                <li>
                  <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
                </li>
                <li>
                  <a href="#" target="_blank"><i class="fab fa-linkedin"></i></a>
                </li>
                <li>
                  <a href="#" target="_blank"><i class="fab fa-dribbble"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end copyright -->

    <!-- jquery -->
    <script src="{% static 'assets/js/jquery-1.11.3.min.js' %}"></script>
    <!-- bootstrap -->
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- count down -->
    <script src="{% static 'assets/js/jquery.countdown.js' %}"></script>
    <!-- isotope -->
    <script src="{% static 'assets/js/jquery.isotope-3.0.6.min.js' %}"></script>
    <!-- waypoints -->
    <script src="{% static 'assets/js/waypoints.js' %}"></script>
    <!-- owl carousel -->
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <!-- magnific popup -->
    <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    <!-- mean menu -->
    <script src="{% static 'assets/js/jquery.meanmenu.min.js' %}"></script>
    <!-- sticker js -->
    <script src="{% static 'assets/js/sticker.js' %}"></script>
    <!-- main js -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'assets/js/jquery-1.11.3.min.js' %}"></script>
    <!-- bootstrap -->
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- count down -->
    <script src="{% static 'assets/js/jquery.countdown.js' %}"></script>
    <!-- isotope -->
    <script src="{% static 'assets/js/jquery.isotope-3.0.6.min.js' %}"></script>
    <!-- waypoints -->
    <script src="{% static 'assets/js/waypoints.js' %}"></script>
    <!-- owl carousel -->
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <!-- magnific popup -->
    <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    <!-- mean menu -->
    <script src="{% static 'assets/js/jquery.meanmenu.min.js' %}"></script>
    <!-- sticker js -->
    <script src="{% static 'assets/js/sticker.js' %}"></script>
    <!-- main js -->
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>

frontend/templates/partials/product_list.html
{% for product in products %}
<div class="col-lg-4 col-md-6 text-center product-item {{ product.type|lower }}" data-price="{{ product.price }}">
  <div class="single-product-item">
    <div class="product-image" style="height: 250px; margin-bottom: 50px">
      <a href="{% url 'core:single_product' product.id %}">
        <img src="{{ product.image.url }}" alt="{{ product.name }}" style="max-height: 210px !important; max-width: 210px !important" />
      </a>
    </div>
    <h3>{{ product.name }}</h3>
    <p class="product-price"><span>{{ product.type.split|first }}</span> ₱{{ product.price }}</p>
    <a href="#" class="cart-btn add-to-cart" data-product-id="{{ product.id }}"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
  </div>
</div>
{% endfor %}